### ISSUE TITLE
swig build forward plan

### ISSUE THREAD

**Issue by cdaringe** [node-swig/swig#1]
This is a continuation of the conversation held [over on paul's swig branch](https://github.com/paularmstrong/swig/issues/628).

Are there any wanting to take over the primary maintainer position?

**Comment by atian25** [comment]
cool

**Comment by mrazvan92** [comment]
:+1:

**Comment by paulcpederson** [comment]
I'm not sure I'd like to be a primary maintainer, but I would love to contribute if possible!

**Comment by Lochlan** [comment]
I am using this code in production so I have an interest in seeing this project remain alive.  If this forked repo is going to be the official repo then I recommend turning on Travis and [fixing tests](https://github.com/paularmstrong/swig/pull/633).  I can help with this effort if you want to give me access to this repo.

Keeping this project alive will be much simpler if we can get buy in from @paularmstrong, so I suggest building some trust there by getting bugs fixed.  And maybe he'll transfer the original repo to this org if enough trust is built.  Not sure what @cdaringe's goals are here exactly but if this repo is at least making some forward progress on the project then that would be a good improvement over the official repo where no PRs are currently being accepted.

**Comment by robgibbons** [comment]
I would be interested in assisting with testing, bug fixing, etc. I've used Swig in multiple projects (no longer under my control) and I would love to see it continued.

**Comment by Lochlan** [comment]
IMO the best way to demonstrate an interest in testing, bug fixing, etc. is to help with testing, bug fixing, etc.—which, thanks to the nature of open source, is as easy as opening a PR!

@robgibbons @paulcpederson if you want to make some contributions and open a PR here or against [the "official" repo](https://github.com/paularmstrong/swig) that sounds like a good place to start and could potentially help build confidence that there is actual momentum here.  It is demotivating that there isn't clearly a place where PRs are being reviewed and accepted, so maybe this fork can be that.  (Should we find out together?)  Make a patch and open a PR against both repos!  Just a suggestion :)

**Comment by paulcpederson** [comment]
@Lochlan can you open https://github.com/paularmstrong/swig/pull/633 against this fork? It looks like you fixed the errors I'm getting with the tests as part of that pr.

**Comment by Lochlan** [comment]
@paulcpederson reopened here as #3

**Comment by paulcpederson** [comment]
:+1:

**Comment by paulrad** [comment]
I'm in ;) Best and simpliest tpl engine ever

**Comment by Smashpipe** [comment]
We love Swig and will support the project any way we can!  If anyone needs resources let us know and we'll figure out a way to make it happen.

**Comment by cdaringe** [comment]
thanks @Smashpipe!

to @all, it's evident that the community still has a lot of love for this package, which is excellent.  land a PR or two (fix a bug, improve the site page, etc), and we'll get you on the collaborator list if you're willing.  we'll still need to dial down a merge strategy, but i'm thinking that "at least two +1"s from collabs is a simple, great way to go.
