### ISSUE TITLE
Set up Travis

### ISSUE THREAD

**Issue by Lochlan** [node-swig/swig#2]
Please set this up: https://travis-ci.org/node-swig/swig
...and make [the relevant badge update in the README](https://github.com/node-swig/swig/blame/5df868471995821fe79c6d646bb729e02c9fed0a/README.md#L1).

**Comment by cdaringe** [comment]
done n did! thanks!

**Comment by cdaringe** [comment]
ps, just been _slammed_ this week, hence the delayed response.  hopefully you have admin rights now
